
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vddqbinlftnnsgtnbvym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZHFiaW5sZnRubnNndG5idnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDc2NDIsImV4cCI6MjA1OTAyMzY0Mn0.hyss_UKJtdGhsl5hGmrbsh_nh1Iq_y3lL2d5xWYtKwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Enable Row Level Security (RLS) for the relevant tables via SQL commands
// To fix permission issues when inserting data, use SQL commands to create appropriate RLS policies
// Note: Ces politiques ont été mises en place (voir les SQL queries exécutées)
