
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vddqbinlftnnsgtnbvym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZHFiaW5sZnRubnNndG5idnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDc2NDIsImV4cCI6MjA1OTAyMzY0Mn0.hyss_UKJtdGhsl5hGmrbsh_nh1Iq_y3lL2d5xWYtKwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// RPC (Remote Procedure Call) functions
// SQL functions that can be called from the client
// Example: upvoteProduct function calls increment_product_upvotes via RPC
/*
CREATE OR REPLACE FUNCTION increment_product_upvotes(product_id UUID)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $$
  UPDATE product_launches
  SET upvotes = upvotes + 1
  WHERE id = product_id;
$$;
*/
